name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      packages: write
    environment: production
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Run tests
      run: npm test
      
    - name: Validate tag format and branch
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        
        # Validate tag format
        if [[ ! $TAG_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid tag format: $TAG_NAME"
          echo "Valid format: v1.0.0, v1.2.3, v2.0.0"
          exit 1
        fi
        echo "Valid tag format: $TAG_NAME"
        
        # Verify tag was created from master branch
        TAG_COMMIT=$(git rev-list -n 1 $TAG_NAME)
        MASTER_COMMIT=$(git rev-list -n 1 origin/master)
        
        if [[ "$TAG_COMMIT" != "$MASTER_COMMIT" ]]; then
          echo "Error: Tag $TAG_NAME was not created from master branch"
          echo "Tag commit: $TAG_COMMIT"
          echo "Master commit: $MASTER_COMMIT"
          exit 1
        fi
        echo "Tag $TAG_NAME is valid and created from master branch"
        
    - name: Bump version
      run: |
        # Extract version from tag (e.g., v1.0.3 -> 1.0.3)
        VERSION=${GITHUB_REF#refs/tags/v}
        npm version $VERSION --no-git-tag-version
        echo "Updated package.json to version $VERSION"
      
    - name: Generate changelog
      id: changelog
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Generate changelog from git commits
        echo "## What's Changed" > CHANGELOG.md
        git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "**Full Changelog**: https://github.com/stackblogger/triggy/compare/$(git describe --tags --abbrev=0 HEAD^)...v$VERSION" >> CHANGELOG.md
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.changelog.outputs.version }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Publish to NPM
      run: npm publish
